#!/usr/bin/env python3
import json

from vault.vault import VaultClient
from vault.helpers import save_secret_to_file


output_path = 'vagrant/shared/secrets.json'


def get_secret(key, vault):
    path = "secret/backup/{key}".format(key=key)
    secret = vault.read_secret(path)
    return key, secret

if __name__ == "__main__":
    vault = VaultClient()
    keys = ["aws_access_key_id", "aws_secret_access_key", "passphrase"]
    secrets = dict(get_secret(k, vault) for k in keys)
    json = json.dumps(secrets, indent="  ", sort_keys=True)

    save_secret_to_file(output_path, json)
    print("Wrote secrets to " + output_path)