# -*- mode: ruby -*-

data_disk_file = 'data_disk.vdi'
data_disk_size = 30 # in GB

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider :virtualbox do |vbox|
    vbox.gui = false
    unless File.exist?(data_disk_file)
      vbox.customize ['createhd', '--filename', data_disk_file,
                      '--variant', 'Fixed',
                      '--size', data_disk_size * 1024]
    end
    vbox.customize ['storageattach', :id, '--storagectl', 'SATA Controller',
                    '--port', 1, '--device', 0, '--type', 'hdd',
                    '--medium', data_disk_file]
    config.vm.provision :shell do |shell|
      shell.path = 'prepare-disk.sh'
    end
  end

  config.vm.provision "shell" do |shell|
    shell.path = "prepare-dependencies.sh"
  end
end
